name: publish
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn jest

      - name: Build
        run: yarn prepare

      - name: Auth NPM
        run:
          git update-index --assume-unchanged .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - name: Release
        run: yarn release

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
